compressionLevel: mixed

enableGlobalCache: true

yarnPath: .yarn/releases/yarn-4.5.1.cjs

# obsidian://open?vault=Vaults&file=David%20Gabison%2FArchive%2FYarn%20pnp%20-%20Typescript%20-%20Cannot%20find%20module
nodeLinker: node-modules
